### ISSUE TITLE
Request: Update blog format

### ISSUE THREAD

**Issue by brianamarie** [githubteacher/githubteacher.github.io#3]
Hello @githubteacher! 

I think it would be ✨ fantastic ✨ to update your portfolio.

Some of my ideas include: 
- [ ] Octocat images :octocat: #5 
- [ ] Links to the On Demand community
- [ ] Resources for how to contribute to open source
- [ ] Resources about GitHub Training
- [ ] New blog posts about GitHub

**Comment by githubteacher** [comment]
@brianamarie, I think those are all good ideas. I will create a project board. Please feel free to start making changes and open some pull requests! 💯

**Comment by crichID** [comment]
> Links to the On Demand community

@githubteacher I :hand: to work on this item!
